
//! Autogenerated weights for `did`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-02-16, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `kostiask-Precision-5550`, CPU: `Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// target/release/qsb-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// did
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// pallets/did/src/default_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

pub trait WeightInfo {
	fn create_did() -> Weight;
	fn add_key() -> Weight;
	fn revoke_key() -> Weight;
	fn deactivate_did() -> Weight;
	fn add_service() -> Weight;
	fn remove_service() -> Weight;
	fn set_metadata() -> Weight;
	fn remove_metadata() -> Weight;
	fn rotate_key() -> Weight;
	fn update_roles() -> Weight;
}

/// Autogenerated benchmark weights for `did`.
pub struct DefaultWeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for DefaultWeightInfo<T> {
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidRecords` (r:1 w:1)
	/// Proof: `Did::DidRecords` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_did() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `60`
		//  Estimated: `3525`
		// Minimum execution time: 132_287_000 picoseconds.
		Weight::from_parts(136_278_000, 0)
			.saturating_add(Weight::from_parts(0, 3525))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::DidRecords` (r:1 w:1)
	/// Proof: `Did::DidRecords` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1402`
		//  Estimated: `4867`
		// Minimum execution time: 136_255_000 picoseconds.
		Weight::from_parts(139_761_000, 0)
			.saturating_add(Weight::from_parts(0, 4867))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::DidRecords` (r:1 w:1)
	/// Proof: `Did::DidRecords` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn revoke_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2719`
		//  Estimated: `6184`
		// Minimum execution time: 138_345_000 picoseconds.
		Weight::from_parts(142_073_000, 0)
			.saturating_add(Weight::from_parts(0, 6184))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::DidRecords` (r:1 w:1)
	/// Proof: `Did::DidRecords` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deactivate_did() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1402`
		//  Estimated: `4867`
		// Minimum execution time: 122_964_000 picoseconds.
		Weight::from_parts(126_296_000, 0)
			.saturating_add(Weight::from_parts(0, 4867))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::DidRecords` (r:1 w:1)
	/// Proof: `Did::DidRecords` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_service() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1402`
		//  Estimated: `4867`
		// Minimum execution time: 122_412_000 picoseconds.
		Weight::from_parts(126_985_000, 0)
			.saturating_add(Weight::from_parts(0, 4867))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::DidRecords` (r:1 w:1)
	/// Proof: `Did::DidRecords` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_service() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1433`
		//  Estimated: `4898`
		// Minimum execution time: 125_453_000 picoseconds.
		Weight::from_parts(130_162_000, 0)
			.saturating_add(Weight::from_parts(0, 4898))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::DidRecords` (r:1 w:1)
	/// Proof: `Did::DidRecords` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1402`
		//  Estimated: `4867`
		// Minimum execution time: 124_546_000 picoseconds.
		Weight::from_parts(129_374_000, 0)
			.saturating_add(Weight::from_parts(0, 4867))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::DidRecords` (r:1 w:1)
	/// Proof: `Did::DidRecords` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1408`
		//  Estimated: `4873`
		// Minimum execution time: 124_011_000 picoseconds.
		Weight::from_parts(138_002_000, 0)
			.saturating_add(Weight::from_parts(0, 4873))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::DidRecords` (r:1 w:1)
	/// Proof: `Did::DidRecords` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn rotate_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2719`
		//  Estimated: `6184`
		// Minimum execution time: 142_193_000 picoseconds.
		Weight::from_parts(146_196_000, 0)
			.saturating_add(Weight::from_parts(0, 6184))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::DidRecords` (r:1 w:1)
	/// Proof: `Did::DidRecords` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_roles() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2719`
		//  Estimated: `6184`
		// Minimum execution time: 134_863_000 picoseconds.
		Weight::from_parts(135_700_000, 0)
			.saturating_add(Weight::from_parts(0, 6184))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

impl WeightInfo for () {
	fn create_did() -> Weight {
		Weight::from_parts(136_278_000, 0)
			.saturating_add(Weight::from_parts(0, 3525))
	}

	fn add_key() -> Weight {
		Weight::from_parts(139_761_000, 0)
			.saturating_add(Weight::from_parts(0, 4867))
	}

	fn revoke_key() -> Weight {
		Weight::from_parts(142_073_000, 0)
			.saturating_add(Weight::from_parts(0, 6184))
	}

	fn deactivate_did() -> Weight {
		Weight::from_parts(126_296_000, 0)
			.saturating_add(Weight::from_parts(0, 4867))
	}

	fn add_service() -> Weight {
		Weight::from_parts(126_985_000, 0)
			.saturating_add(Weight::from_parts(0, 4867))
	}

	fn remove_service() -> Weight {
		Weight::from_parts(130_162_000, 0)
			.saturating_add(Weight::from_parts(0, 4898))
	}

	fn set_metadata() -> Weight {
		Weight::from_parts(129_374_000, 0)
			.saturating_add(Weight::from_parts(0, 4867))
	}

	fn remove_metadata() -> Weight {
		Weight::from_parts(138_002_000, 0)
			.saturating_add(Weight::from_parts(0, 4873))
	}

	fn rotate_key() -> Weight {
		Weight::from_parts(146_196_000, 0)
			.saturating_add(Weight::from_parts(0, 6184))
	}

	fn update_roles() -> Weight {
		Weight::from_parts(135_700_000, 0)
			.saturating_add(Weight::from_parts(0, 6184))
	}
}
